/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package misiontic.ciclo2.semana7.universidad.mvc.vista.gui;

/**
 *
 * @author emanuel
 */
public class PanelProfesor extends javax.swing.JPanel {

    /**
     * Creates new form PanelProfesor
     */
    public PanelProfesor() {
        initComponents();
    }

    public void limpiarPantalla(){
        textCedula.setText("");
        textPrimerNombre.setText("");
        textSegundoNombre.setText("");
        textPrimerApellido.setText("");
        textSegundoApellido.setText("");
        textTelefono.setText("");
        textOficina.setText("");
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        textCedula = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        textPrimerNombre = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        textSegundoNombre = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        textPrimerApellido = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        textSegundoApellido = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        textTelefono = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        textOficina = new javax.swing.JTextField();

        setLayout(new java.awt.GridLayout(7, 2));

        jLabel5.setText("Cedula");
        add(jLabel5);
        add(textCedula);

        jLabel1.setText("Primer nombre");
        add(jLabel1);
        add(textPrimerNombre);

        jLabel2.setText("Segundo nombre");
        add(jLabel2);
        add(textSegundoNombre);

        jLabel3.setText("Primer apellido");
        add(jLabel3);
        add(textPrimerApellido);

        jLabel4.setText("Segundo apellido");
        add(jLabel4);
        add(textSegundoApellido);

        jLabel6.setText("Teléfono");
        add(jLabel6);
        add(textTelefono);

        jLabel7.setText("Oficina");
        add(jLabel7);
        add(textOficina);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField textCedula;
    private javax.swing.JTextField textOficina;
    private javax.swing.JTextField textPrimerApellido;
    private javax.swing.JTextField textPrimerNombre;
    private javax.swing.JTextField textSegundoApellido;
    private javax.swing.JTextField textSegundoNombre;
    private javax.swing.JTextField textTelefono;
    // End of variables declaration//GEN-END:variables
}
