/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package misiontic.ciclo2.semana4.nomina;

/**
 *
 * @author emanuel
 */
public class PanelEmpleado extends javax.swing.JPanel {

    /**
     * Creates new form PanelAsalariado
     */
    public PanelEmpleado() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelNombre = new javax.swing.JLabel();
        textNombre = new javax.swing.JTextField();
        labelCodigo = new javax.swing.JLabel();
        textCodigo = new javax.swing.JTextField();

        setPreferredSize(new java.awt.Dimension(300, 60));
        setLayout(new java.awt.GridLayout(2, 2));

        labelNombre.setText("Nombre:");
        add(labelNombre);
        add(textNombre);

        labelCodigo.setText("Codigo:");
        add(labelCodigo);
        add(textCodigo);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel labelCodigo;
    private javax.swing.JLabel labelNombre;
    private javax.swing.JTextField textCodigo;
    private javax.swing.JTextField textNombre;
    // End of variables declaration//GEN-END:variables
}
