/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package misiontic.ciclo2.semana4.figuras;

import misiontic.ciclo2.semana3.herencia.figuras.Circulo;
import misiontic.ciclo2.semana3.herencia.figuras.Cuadrado;

/**
 *
 * @author emanuel
 */
public class CirculoPanel extends FiguraPanel {

    /**
     * Creates new form CirculoPanel
     */
    public CirculoPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lRadio = new javax.swing.JLabel();
        tRadio = new javax.swing.JTextField();

        lRadio.setText("Radio:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lRadio)
                .addGap(4, 4, 4)
                .addComponent(tRadio, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lRadio)
                    .addComponent(tRadio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lRadio;
    private javax.swing.JTextField tRadio;
    // End of variables declaration//GEN-END:variables

    
    @Override
    public double getArea(){
        if(tRadio.getText().equals("")){
            return 0.0;
        }
        double radio = Double.parseDouble(tRadio.getText());
        this.figura = new Circulo(radio);
        return figura.calcularArea();
    }
    
    @Override
    public double getPerimetro(){
        if(tRadio.getText().equals("")){
            return 0.0;
        }
        double radio = Double.parseDouble(tRadio.getText());
        this.figura = new Circulo(radio);
        return figura.calcularArea();
    }
}
