/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package misiontic.ciclo2.semana7.universidad.mvc.vista.gui.alumno;

import javax.swing.JButton;

/**
 *
 * @author emanuel
 */
public class PanelBotonesAlumno extends javax.swing.JPanel {

    /**
     * Creates new form PanelBotonesAlumno
     */
    public PanelBotonesAlumno() {
        initComponents();
    }

    public JButton getBtnActualizar() {
        return btnActualizar;
    }

    public JButton getBtnBuscar() {
        return btnBuscar;
    }

    public JButton getBtnCrear() {
        return btnCrear;
    }

    public JButton getBtnEliminar() {
        return btnEliminar;
    }

    public JButton getBtnListar() {
        return btnListar;
    }

    public JButton getBtnLimpiar() {
        return btnLimpiar;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnCrear = new javax.swing.JButton();
        btnBuscar = new javax.swing.JButton();
        btnActualizar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnListar = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();

        setLayout(new java.awt.GridLayout(1, 6));

        btnCrear.setText("Crear");
        add(btnCrear);

        btnBuscar.setText("Buscar");
        add(btnBuscar);

        btnActualizar.setText("Actualizar");
        add(btnActualizar);

        btnEliminar.setText("Eliminar");
        add(btnEliminar);

        btnListar.setText("Listar");
        add(btnListar);

        btnLimpiar.setText("Limpiar");
        add(btnLimpiar);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizar;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnCrear;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnListar;
    // End of variables declaration//GEN-END:variables
}
