/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package misiontic.ciclo2.semana7.universidad;

import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author emanuel
 */
public class AlumnoGUI extends javax.swing.JFrame {

    PruebaUniversidad prueba;
    /**
     * Creates new form AlumnoGUI
     */
    public AlumnoGUI() {
        initComponents();
        prueba = new PruebaUniversidad();
        prueba.crearConnection();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        primerNombreText = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        segundoNombreText = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        primerApellidoText = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        segundoApellidoText = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        cedulaText = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        edadText = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        semestreText = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.GridLayout(8, 2));

        jLabel1.setText("primer nombre");
        getContentPane().add(jLabel1);
        getContentPane().add(primerNombreText);

        jLabel2.setText("segundo nombre");
        getContentPane().add(jLabel2);
        getContentPane().add(segundoNombreText);

        jLabel3.setText("primer apellido");
        getContentPane().add(jLabel3);
        getContentPane().add(primerApellidoText);

        jLabel4.setText("segundo apellido");
        getContentPane().add(jLabel4);
        getContentPane().add(segundoApellidoText);

        jLabel5.setText("cedula");
        getContentPane().add(jLabel5);
        getContentPane().add(cedulaText);

        jLabel6.setText("edad");
        getContentPane().add(jLabel6);
        getContentPane().add(edadText);

        jLabel7.setText("semestre");
        getContentPane().add(jLabel7);
        getContentPane().add(semestreText);

        jButton1.setText("Agregar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {            
            //Hacer las validaciones
            
            // TODO add your handling code here:
            Alumno alumno = new Alumno();
            alumno.setPrimerNombre(primerNombreText.getText());
            alumno.setSegundoNombre(segundoNombreText.getText());
            alumno.setPrimerApellido(primerApellidoText.getText());
            alumno.setSegundoApellido(segundoApellidoText.getText());
            int cedula = Integer.parseInt(cedulaText.getText());
            alumno.setCedula(cedula);
            int semestre = Integer.parseInt(semestreText.getText());
            alumno.setSemestre(semestre);
            int edad = Integer.parseInt(edadText.getText());
            alumno.setEdad(edad);
            prueba.insertarAlumno(alumno);
            System.out.println("Registro agregado");
            limpiarGUI();
        } catch (SQLException ex) {
            Logger.getLogger(AlumnoGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    
    private void limpiarGUI(){
        primerNombreText.setText("");
        segundoNombreText.setText("");
        primerApellidoText.setText("");
        segundoApellidoText.setText("");
        cedulaText.setText("");
        edadText.setText("");
        semestreText.setText("");
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AlumnoGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AlumnoGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AlumnoGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AlumnoGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AlumnoGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField cedulaText;
    private javax.swing.JTextField edadText;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField primerApellidoText;
    private javax.swing.JTextField primerNombreText;
    private javax.swing.JTextField segundoApellidoText;
    private javax.swing.JTextField segundoNombreText;
    private javax.swing.JTextField semestreText;
    // End of variables declaration//GEN-END:variables
}
